# Generated by Django 6.0.2 on 2026-03-14 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('our_order_no', models.CharField(blank=True, max_length=100)),
                ('our_reference', models.CharField(blank=True, max_length=100)),
                ('end_user', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'enduser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_enduser', to='partners.partner')),
                ('importer', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'importer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_importer', to='partners.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.commercialinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('our_reference', models.CharField(blank=True, max_length=100)),
                ('end_user', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'enduser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_enduser', to='partners.partner')),
                ('importer', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'importer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_importer', to='partners.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.proformainvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
