# Generated by Django 6.0.2 on 2026-03-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_commercialinvoiceitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoiceitem',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
