# Generated by Django 6.0.2 on 2026-03-21 13:59

from django.db import migrations, models


def copy_hs_code_to_proforma(apps, schema_editor):
    ProformaInvoice = apps.get_model("invoices", "ProformaInvoice")
    ProformaInvoiceItem = apps.get_model("invoices", "ProformaInvoiceItem")

    for proforma in ProformaInvoice.objects.all():
        item = (
            ProformaInvoiceItem.objects
            .filter(invoice_id=proforma.pk)
            .exclude(hs_code="")
            .order_by("id")
            .first()
        )

        if item:
            proforma.hs_code = item.hs_code
            proforma.save(update_fields=["hs_code"])


def copy_hs_code_back_to_items(apps, schema_editor):
    ProformaInvoice = apps.get_model("invoices", "ProformaInvoice")
    ProformaInvoiceItem = apps.get_model("invoices", "ProformaInvoiceItem")

    for proforma in ProformaInvoice.objects.exclude(hs_code=""):
        ProformaInvoiceItem.objects.filter(invoice_id=proforma.pk).update(
            hs_code=proforma.hs_code
        )


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_commercialinvoiceitem_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(copy_hs_code_to_proforma, copy_hs_code_back_to_items),
        migrations.RemoveField(
            model_name='proformainvoiceitem',
            name='hs_code',
        ),
    ]
