# Generated by Django 6.0.2 on 2026-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_proforma_item_hs_code_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='price_for',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
