# Generated by Django 6.0.2 on 2026-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_proformainvoice_price_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='item_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
