# Generated by Django 6.0.2 on 2026-04-13 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_proformainvoiceitem_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='item_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
