# Generated by Django 6.0.2 on 2026-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_proformainvoiceitem_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='item_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
