# Generated by Django 6.0.2 on 2026-04-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_alter_proformainvoiceitem_item_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialinvoice",
            name="dispatching_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="commercialinvoice",
            name="packing_specification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CommercialInvoicePacking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_packing", models.CharField(blank=True, max_length=255)),
                ("gross_weight", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("net_weight", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("dimension_length", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("dimension_width", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("dimension_height", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_entries",
                        to="invoices.commercialinvoice",
                    ),
                ),
            ],
        ),
    ]
