# Generated by Django 6.0.2 on 2026-04-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_commercialinvoice_packing'),
        ('products', '0004_product_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_items', to='products.product'),
        ),
    ]
