# Generated by Django 5.2.12 on 2026-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoiceitem_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
