# Generated by Django 6.0.2 on 2026-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoiceitem_quantity_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
