# Generated by Codex on 2026-07-20

from django.db import migrations, models


def copy_company_terms_to_existing_invoices(apps, schema_editor):
    CompanySetting = apps.get_model("company", "CompanySetting")
    ProformaInvoice = apps.get_model("invoices", "ProformaInvoice")
    CommercialInvoice = apps.get_model("invoices", "CommercialInvoice")

    company = CompanySetting.objects.first()
    if not company:
        return

    ProformaInvoice.objects.filter(delivery_time="").update(delivery_time=company.delivery_time)
    ProformaInvoice.objects.filter(terms_conditions="").update(terms_conditions=company.terms_conditions)
    CommercialInvoice.objects.filter(delivery_time="").update(delivery_time=company.delivery_time)
    CommercialInvoice.objects.filter(terms_conditions="").update(terms_conditions=company.terms_conditions)


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companysetting_president"),
        ("invoices", "0016_alter_commercialinvoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialinvoice",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="commercialinvoice",
            name="terms_conditions",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="terms_conditions",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_company_terms_to_existing_invoices, migrations.RunPython.noop),
    ]
