# Generated by Codex on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0017_invoice_delivery_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialinvoice",
            name="price_for",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
