# Generated by Django 6.0.2 on 2026-07-29 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_commercialinvoice_price_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoicepacking',
            name='dimension_height',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='commercialinvoicepacking',
            name='dimension_length',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='commercialinvoicepacking',
            name='dimension_width',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='commercialinvoicepacking',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='commercialinvoicepacking',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=11),
        ),
    ]
