# Generated by Django 6.0.2 on 2026-03-14 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('sent_by', models.CharField(blank=True, max_length=255)),
                ('shipment', models.CharField(blank=True, max_length=255)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sales_condition', models.CharField(blank=True, max_length=255)),
                ('payment_condition', models.CharField(blank=True, max_length=255)),
                ('delivery_terms', models.CharField(blank=True, max_length=255)),
                ('requester', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'requester'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_requester', to='partners.partner')),
                ('seller', models.ForeignKey(limit_choices_to={'partner_type': 'seller'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_seller', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
        ),
    ]
