# Generated by Django 6.0.2 on 2026-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseorderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
