# Generated by Django 6.0.2 on 2026-04-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('purchase', '0003_purchaseorderitem_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'seller'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_seller', to='partners.partner'),
        ),
    ]
