# Generated by Django 6.0.2 on 2026-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchaseorderitem_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
