# Generated by Django 6.0.2 on 2026-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('year', models.IntegerField(default=2026)),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=100)),
                ('company_fax', models.CharField(blank=True, max_length=100)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('footer_order', models.TextField(blank=True)),
                ('siren', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=100)),
                ('bic', models.CharField(blank=True, max_length=100)),
                ('footer_invoice', models.CharField(blank=True, max_length=255)),
                ('invoice_note', models.TextField(blank=True)),
                ('delivery_time', models.CharField(blank=True, max_length=255)),
                ('terms_conditions', models.CharField(blank=True, max_length=255)),
                ('proforma_validity', models.IntegerField(default=7, help_text='Number of days before proforma expires')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'USD'), ('CNY', 'Yuan'), ('MAD', 'Dirham'), ('LBP', 'Lear'), ('IRR', 'Rls')], default='EUR', max_length=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
            ],
        ),
    ]
