# Generated by Django 6.0.2 on 2026-04-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR - Euro'), ('USD', 'USD - US Dollar'), ('CNY', 'CNY - Chinese Yuan'), ('MAD', 'MAD - Moroccan Dirham'), ('LBP', 'LBP - Lebanese Pound'), ('IRR', 'IRR - Iranian Rial')], default='EUR', max_length=10),
        ),
    ]
