# Generated by Django 6.0.2 on 2026-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_companysetting_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="president",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
