# Generated by Codex on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="part_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
